### ISSUE TITLE
AOSP on k50u with no kernel

### ISSUE THREAD

**Issue by trinhloivn** [diting-development/android_device_xiaomi_diting-kernel#1]
https://forum.xda-developers.com/t/port-shared-rom-13-derpfest-13-unofficial-xiaomi-12t-pro-redmi-k50-ultra.4603043/

hello, 
currently on k50 ultra there is no open kernel.
So no aosp rom.
but now with rom on k60, it works stably on k50 ultra, with system,system_ext,product partitions. 
but there are 2  current error is fod,fastcharge [only<10W], 
I see u are k50u kernel developer can you fix it? 
very grateful

**Comment by kindle4jerry** [comment]
These problem are not on kernel. Some drivers are not in kernel.
Today, xiaomi used Android Common Kernel, you can flash an ACK by yourself.
For example, you can flash KernelSU to get root. It works well. I did.

We are trying to use prebuilt kernel and some prebuilt files, you can see them on this repository.
Good luck!
